// Generated by scripts/vite-data-store.ts. App shell only; data files are cached by the page (iit-data-v1).
const VERSION = "0e9b5ec681a7";
const SHELL = ["about-en.html","about.html","app.html","app.webmanifest","assets/FilterBench-D9o8Av4c.js","assets/VerifyPanel-GxwoqkfT.js","assets/app-CA6g3Tvj.js","assets/boot-C4SVIA0c.js","assets/boot-d_qygRTk.css","assets/favicon-Cr225KxK.svg","assets/i18n-data-en-CUgHkGzP.js","assets/i18n-en-Z410tuYa.js","assets/ibm-plex-mono-latin-400-DMJ8VG8y.woff2","assets/ibm-plex-mono-latin-600-BgSNZQsw.woff2","assets/ibm-plex-sans-latin-400-CDDApCn2.woff2","assets/ibm-plex-sans-latin-500-6ng42L7E.woff2","assets/ibm-plex-sans-latin-600-CuJfVYMP.woff2","assets/iit-engrave-BuzTOdGH.woff2","assets/snapshot-sheet-8IjASk3h.js","assets/spectral-worker-DsJdeUE2.js","assets/vendor-D5j7eyu-.js","icons/apple-touch-icon.png","icons/icon-192.png","icons/share-thumb.jpg","product.json"];
const scope = new URL(self.registration.scope);
// Per site path, so a copy under a sub-folder (e.g. a staging build) never removes this one's cache.
const PREFIX = 'iit-shell:' + scope.pathname + ':', CACHE = PREFIX + VERSION;
const PAGE = new URL('app.html', scope).href;
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => Promise.all(SHELL.map(async f => {
    const url = new URL(f, scope).href;
    // Content-hashed files (assets/) that did not change since the previous build: reuse that copy.
    const old = f.startsWith('assets/') ? await caches.match(url) : undefined;
    if (old) return cache.put(url, old);
    const response = await fetch(new Request(url, { cache: 'reload' }));
    if (!response.ok) throw new Error(f + ': HTTP ' + response.status);
    return cache.put(url, response);
  }))));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => (k.startsWith(PREFIX) && k !== CACHE) || k.startsWith('iit-shell-')).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('message', event => { if (event.data === 'skip-waiting') self.skipWaiting(); });
self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return;
  const path = url.pathname.slice(scope.pathname.length);
  if (path.startsWith('data/')) return;
  // The simulator page (index.html is the same file on the published site): this build's copy, network if missing.
  const key = request.mode === 'navigate' && /^(index\.html|app\.html)?$/.test(path) ? PAGE : SHELL.includes(path) ? new URL(path, scope).href : null;
  if (!key) return;
  event.respondWith(caches.open(CACHE).then(cache => cache.match(key)).then(hit => hit || fetch(request)));
});
