// Generated by scripts/vite-data-store.ts. App shell only; data files are cached by the page (iit-data-v1).
const VERSION = "c036b02e5b1b";
const SHELL = ["about-en.html","about.html","app.html","app.webmanifest","assets/FilterBench-DbUSovJI.js","assets/VerifyPanel-_MWz96QX.js","assets/app-BJYmEgdS.js","assets/boot-BYVNxJPA.js","assets/boot-D3h66oHO.css","assets/favicon-Cr225KxK.svg","assets/hosting-fHzMXklU.js","assets/i18n-data-en-bQSvY8c0.js","assets/i18n-en-BD3S5GY4.js","assets/ibm-plex-mono-latin-400-DMJ8VG8y.woff2","assets/ibm-plex-mono-latin-600-BgSNZQsw.woff2","assets/ibm-plex-sans-latin-400-CDDApCn2.woff2","assets/ibm-plex-sans-latin-500-6ng42L7E.woff2","assets/ibm-plex-sans-latin-600-CuJfVYMP.woff2","assets/iit-engrave-Cjtkfhv5.woff2","assets/sky-worker-BPRRUAwP.js","assets/snapshot-sheet-CFDbKX3F.js","assets/spectral-worker-DnFd-1e3.js","assets/vendor--Do4GtAm.js","icons/apple-touch-icon.png","icons/icon-192.png","icons/share-thumb.jpg","product.json"];
const scope = new URL(self.registration.scope);
// Per site path, so a copy under a sub-folder (e.g. a staging build) never removes this one's cache.
const PREFIX = 'iit-shell:' + scope.pathname + ':', CACHE = PREFIX + VERSION;
const PAGE = new URL('app.html', scope).href;
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => Promise.all([...SHELL, 'hosting.json'].map(async f => {
    const url = new URL(f, scope).href;
    // Content-hashed files (assets/) that did not change since the previous build: reuse that copy.
    const old = f.startsWith('assets/') ? await caches.match(url) : undefined;
    if (old) return cache.put(url, old);
    // Content-hashed assets the page has just loaded come from the HTTP cache instead of a second download.
    const response = await fetch(new Request(url, { cache: f.startsWith('assets/') ? 'default' : 'reload' }));
    if (f === 'hosting.json' && response.status === 404) return; // unsplit local build
    if (!response.ok) throw new Error(f + ': HTTP ' + response.status);
    return cache.put(url, response);
  }))));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => (k.startsWith(PREFIX) && k !== CACHE) || k.startsWith('iit-shell-')).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('message', event => { if (event.data === 'skip-waiting') self.skipWaiting(); });
self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  // Requests from a controlled client include same-origin sibling Pages packages and their workers.
  if (url.origin === scope.origin && /(?:\.[0-9a-f]{16}\.(?:json|bin|gz)(?:\.gz)+|package-manifest\.[0-9a-f]{16}\.json)$/.test(url.pathname)) {
    // A Range request (0.9.47 segmented downloads) asks for one piece, not the file: caching it under the file's URL
    // would answer every later piece with the first one. The page caches the assembled, verified file itself.
    if (request.headers.has('range')) return;
    event.respondWith(caches.open('iit-data-v1').then(async cache => {
      const hit = await cache.match(request); if (hit) return hit;
      const r = await fetch(request);
      if (r.ok) { const body = await r.clone().arrayBuffer(); await cache.put(request, new Response(body, { headers: { 'content-type': r.headers.get('content-type') || 'application/octet-stream', 'x-iit-bytes': String(body.byteLength), 'x-iit-stored': String(Date.now()) } })); }
      return r;
    })); return;
  }
  if (url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return;
  const path = url.pathname.slice(scope.pathname.length);
  if (path === 'hosting.json') {
    event.respondWith(caches.open(CACHE).then(async cache => {
      try { const r = await fetch(new Request(request, { cache: 'no-cache' })); if (r.ok) await cache.put(request, r.clone()); return r; }
      catch (e) { const old = await cache.match(request); if (old) return old; throw e; }
    })); return;
  }
  if (path.startsWith('data/')) return;
  // Images of this build (not precached): cached in the shell cache on first use, offline afterwards.
  if (/^assets\/.*\.webp$/.test(path)) {
    event.respondWith(caches.open(CACHE).then(async cache => {
      const hit = await cache.match(request); if (hit) return hit;
      const r = await fetch(request); if (r.ok) await cache.put(request, r.clone()).catch(() => {}); return r;
    })); return;
  }
  // The simulator page (index.html is the same file on the published site): this build's copy, network if missing.
  const key = request.mode === 'navigate' && /^(index\.html|app\.html)?$/.test(path) ? PAGE : SHELL.includes(path) ? new URL(path, scope).href : null;
  if (!key) return;
  event.respondWith(caches.open(CACHE).then(cache => cache.match(key)).then(hit => hit || fetch(request)));
});
